name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Build with Maven
      run: cd packagepal && mvn clean install

    - name: Run tests
      run: cd packagepal && mvn test

    - name: Set up H2 Database
      run: cd packagepal && mvn spring-boot:start

    - name: Run database migrations
      run: cd packagepal && mvn flyway:migrate

    - name: Stop H2 Database
      run: cd packagepal && mvn spring-boot:stop
